sudo: required

services:
  - docker

script:
  - docker build -t ysoffner/ionic-docker .
  - docker run ysoffner/ionic-docker /bin/sh -c "ionic -v && ionic config set -g backend legacy && ionic start test blank --no-link --no-git --cordova && cd test && ionic cordova platform add android --no-resources && ionic cordova build android"