sudo: required

services:
  - docker

matrix:
  fast_finish: true
  include:
    - env:
      - VERSION=1.0.0

before_script:
  - docker build -t ysoffner/ionic-docker .
  - docker run -ti --rm -p 8100:8100 -p 35729:35729 ysoffner/ionic-docker /bin/sh -c "ionic -v"